// Python IDE feature — a multi-file Python mini-IDE in the browser with Pyodide + CodeMirror
// (self-hosted, no CDN). Drop-in feature module: `components` overrides ToolStub for /python,
// the `py.*` i18n strings are merged into useI18n, and register() wires a ⌘K command to jump in.
//
// This file MUST stay light and side-effect-free at import time: no window/document/pyodide
// access, and it MUST NOT import useI18n (circular). The heavy Pyodide runtime + CodeMirror are
// lazy-loaded inside PythonIDE (via ./pythonRunner and ./cmEditor). Pure descriptors come from
// ./pythonHelpers and ./fileModel, which are also SSG/node-safe.
import { registerCommand } from '../../composables/useCommands'

const Page = () => import('./PythonPage.vue')

export default {
  components: {
    '/python': Page,
  },

  i18n: {
    en: {
      'py.title': 'Python IDE',
      'py.hint': 'A multi-file Python IDE in your browser, powered by Pyodide — no server, nothing uploaded.',
      'py.placeholder': '# Write Python here, then press Run (Cmd/Ctrl+Enter)\nprint("Hello, world")',
      'py.examples': 'Examples',
      'py.files': 'Files',
      'py.newFile': 'New file',
      'py.deleteFile': 'Delete file',
      'py.renameHint': 'Double-click to rename',
      'py.fileError': 'Could not create file',
      'py.fileDuplicate': 'A file with that name already exists',
      'py.fileInvalid': 'Invalid name — use letters, digits, _ and a .py extension',
      'py.cantDeleteLast': 'Keep at least one file',
      'py.outputEmpty': 'Run your code to see output here.',
      'py.run': 'Run',
      'py.stop': 'Stop',
      'py.stopHint': 'Force-stop the running program (terminates the runtime)',
      'py.stopped': '⏹ Stopped by user. The runtime will restart on the next run.',
      'py.restarting': 'Restarting Python runtime…',
      'py.running': 'Running…',
      'py.loadingCore': 'Loading Python runtime…',
      'py.downloadingCore': 'Downloading Python runtime',
      'py.initRuntime': 'Starting Python…',
      'py.coreNotice': 'First run downloads the ~12MB Python runtime from the official Pyodide CDN. It is cached durably (Cache API), so later runs and reloads are instant — offline-fast.',
      'py.coreNoticeCached': 'Python runtime is cached locally — starting up will be instant, no re-download.',
      'py.console': 'Output',
      'py.stdinPlaceholder': 'Type input for input() and press Enter…',
      'py.stdinSend': 'Send',
      'py.stdinHint': 'Feeds the next input() call from the in-page terminal (never a browser dialog). Type a line and press Enter; pre-type lines before Run to answer multiple prompts.',
      'py.waitingInput': 'Program is waiting for input — type here and press Enter…',
      'py.preview': 'Web preview',
      'py.previewExperimental': 'Experimental',
      'py.previewHint': 'Routes a synthetic request to your web app in-interpreter — WSGI (Flask) or ASGI (FastAPI). No real socket.',
      'py.previewGo': 'Go',
      'py.previewNoApp': 'No web app detected. Define a callable named app — a WSGI app (Flask) or an ASGI app (FastAPI()) — and run again.',
      'py.previewPath': 'Path, e.g. / or /items?limit=2',
      'py.previewStatus': 'Status',
      'py.previewEmpty': 'Enter a path and press Go to render a response.',
      'py.openPreview': 'Open web preview',
      'py.dismissPreview': 'Close preview',
      'py.openInWindow': 'Open in new window',
      'py.fullscreen': 'Fullscreen',
      'py.exitFullscreen': 'Exit fullscreen',
      'py.popupBlocked': 'Pop-up blocked — allow pop-ups to open the preview in a new window.',
      'py.fsFailed': 'Could not enter fullscreen.',
      'py.explorer': 'Explorer',
      'py.collapse': 'Collapse',
      'py.expand': 'Expand',
      'py.dragResize': 'Drag to resize',
      'py.lastValue': 'Last value',
      'py.figures': 'Figure',
      'py.htmlOutput': 'HTML output',
      'py.noOutput': '(ran with no output)',
      'py.clearOutput': 'Clear output',
      'py.failed': 'Run failed',
      'py.packages': 'Install packages',
      'py.packagesNote': 'Optional & online: micropip fetches wheels from PyPI / jsDelivr over the network. The Python standard library, NumPy and Matplotlib already work fully offline. Cross-origin requests.get() / urlopen() are routed through the site proxy automatically (needs the optional backend).',
      'py.packagesPlaceholder': 'e.g. requests, rich, cowsay',
      'py.install': 'Install',
      'py.installing': 'Installing…',
      'py.installed': 'Installed',
      'py.installFailed': 'Install failed',
      'py.networkBadge': 'Needs network (micropip)',
      'py.packagesManage': 'Packages',
      'py.versionHint': 'Install a specific version with name==x.y.z (micropip). Wheels are cached durably, so re-installs are offline-fast.',
      'py.refresh': 'Refresh',
      'py.uninstall': 'Uninstall',
      'py.uninstalled': 'Uninstalled',
      'py.uninstallFailed': 'Uninstall failed',
      'py.noPkgs': 'No third-party packages installed yet.',
      'py.loadingPkgs': 'Reading installed packages…',
      'py.pkgRunFirst': 'Run your code once to start the runtime, then manage packages here.',
      'py.cacheReady': 'Runtime cached',
      'py.cacheWill': 'Will download once',
      'py.command': 'Open Python IDE',
    },
    zh: {
      'py.title': 'Python IDE',
      'py.hint': '浏览器里的多文件 Python IDE,由 Pyodide 驱动 — 无需服务器,绝不上传。',
      'py.placeholder': '# 在此编写 Python,然后点击运行(Cmd/Ctrl+Enter)\nprint("你好,世界")',
      'py.examples': '示例',
      'py.files': '文件',
      'py.newFile': '新建文件',
      'py.deleteFile': '删除文件',
      'py.renameHint': '双击重命名',
      'py.fileError': '无法创建文件',
      'py.fileDuplicate': '已存在同名文件',
      'py.fileInvalid': '名称无效 — 仅限字母、数字、下划线,且以 .py 结尾',
      'py.cantDeleteLast': '至少保留一个文件',
      'py.outputEmpty': '运行代码后,这里会显示输出。',
      'py.run': '运行',
      'py.stop': '停止',
      'py.stopHint': '强制停止正在运行的程序(终止运行时)',
      'py.stopped': '⏹ 已被用户停止。下次运行时运行时将重新启动。',
      'py.restarting': '正在重启 Python 运行时…',
      'py.running': '运行中…',
      'py.loadingCore': '正在加载 Python 运行时…',
      'py.downloadingCore': '正在下载 Python 运行时',
      'py.initRuntime': '正在启动 Python…',
      'py.coreNotice': '首次运行会从 Pyodide 官方 CDN 下载约 12MB 的 Python 运行时,并通过 Cache API 持久缓存,之后刷新或重新运行都瞬时完成(可离线)。',
      'py.coreNoticeCached': 'Python 运行时已在本地缓存 — 启动将是瞬时的,无需重新下载。',
      'py.console': '输出',
      'py.stdinPlaceholder': '为 input() 输入内容,然后按回车…',
      'py.stdinSend': '发送',
      'py.stdinHint': '在页面内终端为下一个 input() 提供输入(绝不弹出浏览器对话框)。输入一行并按回车;运行前可预先输入多行以回答多个提示。',
      'py.waitingInput': '程序正在等待输入 —— 在此输入并按回车…',
      'py.preview': '网页预览',
      'py.previewExperimental': '实验性',
      'py.previewHint': '在解释器内把一个合成请求路由到你的网页应用 —— WSGI(Flask)或 ASGI(FastAPI)。并非真实套接字。',
      'py.previewGo': '前往',
      'py.previewNoApp': '未检测到网页应用。请定义一个名为 app 的可调用对象 —— WSGI 应用(Flask)或 ASGI 应用(FastAPI())—— 并重新运行。',
      'py.previewPath': '路径,例如 / 或 /items?limit=2',
      'py.previewStatus': '状态',
      'py.previewEmpty': '输入路径并点击「前往」以渲染响应。',
      'py.openPreview': '打开网页预览',
      'py.dismissPreview': '关闭预览',
      'py.openInWindow': '在新窗口打开',
      'py.fullscreen': '全屏',
      'py.exitFullscreen': '退出全屏',
      'py.popupBlocked': '弹窗被拦截 —— 请允许弹出窗口以在新窗口打开预览。',
      'py.fsFailed': '无法进入全屏。',
      'py.explorer': '资源管理器',
      'py.collapse': '收起',
      'py.expand': '展开',
      'py.dragResize': '拖动以调整大小',
      'py.lastValue': '最后的值',
      'py.figures': '图像',
      'py.htmlOutput': 'HTML 输出',
      'py.noOutput': '(运行完成,无输出)',
      'py.clearOutput': '清空输出',
      'py.failed': '运行失败',
      'py.packages': '安装第三方包',
      'py.packagesNote': '可选且联网:micropip 会通过网络从 PyPI / jsDelivr 下载 wheel 包。Python 标准库、NumPy 和 Matplotlib 已可完全离线使用。跨域的 requests.get() / urlopen() 会自动经由站点代理转发(需要可选后端)。',
      'py.packagesPlaceholder': '例如 requests, rich, cowsay',
      'py.install': '安装',
      'py.installing': '安装中…',
      'py.installed': '已安装',
      'py.installFailed': '安装失败',
      'py.networkBadge': '需要联网(micropip)',
      'py.packagesManage': '包管理',
      'py.versionHint': '可用 名称==x.y.z 安装指定版本(micropip)。wheel 包会持久缓存,重装可离线快速完成。',
      'py.refresh': '刷新',
      'py.uninstall': '卸载',
      'py.uninstalled': '已卸载',
      'py.uninstallFailed': '卸载失败',
      'py.noPkgs': '尚未安装任何第三方包。',
      'py.loadingPkgs': '正在读取已安装的包…',
      'py.pkgRunFirst': '先运行一次代码以启动运行时,然后在此管理包。',
      'py.cacheReady': '运行时已缓存',
      'py.cacheWill': '将下载一次',
      'py.command': '打开 Python IDE',
    },
  },

  register() {
    // ⌘K entry. The title resolves through useI18n at palette render time via the t() lookup
    // of the registered key; we set a stable English fallback as the visible title here and a
    // keyword so search matches "python" in either language.
    registerCommand({
      id: 'open-python',
      title: 'Python IDE',
      group: 'Tools',
      keywords: 'python pyodide run code repl ide editor 运行 代码 编辑器',
      needsBackend: false,
      run: () => {
        if (typeof window !== 'undefined') window.location.assign('/python')
      },
    })
  },
}
