// Image suite feature module. Light + side-effect-free at import: only the export object and
// lazy component thunks. Route paths + SEO meta live in src/router/meta.js; this only overrides
// the page components and contributes its i18n strings (namespaced under `img2.*` to avoid
// colliding with the legacy `img.*` keys). No register() needed — the command palette already
// auto-registers every route from ROUTE_META, and these tools run fully client-side (no
// converters to register).

export default {
  components: {
    '/image/compress': () => import('./CompressPage.vue'),
    '/image/convert': () => import('./ConvertPage.vue'),
    '/image/watermark': () => import('./WatermarkPage.vue'),
    '/image/edit': () => import('./EditPage.vue'),
    '/image/compose': () => import('./ComposePage.vue'),
    '/image/metadata': () => import('./MetadataPage.vue'),
    '/image/invisible': () => import('./InvisibleWatermarkPage.vue'),
  },
  i18n: {
    en: {
      // Shared
      'img2.drop': 'Drop an image here',
      'img2.browse': 'Click, drop, or paste · PNG, JPG, WebP, GIF',
      'img2.dropBatch': 'Drop images here',
      'img2.browseBatch': 'Click, drop, or paste · multiple files supported',
      'img2.change': 'Change',
      'img2.remove': 'Remove',
      'img2.clear': 'Clear',
      'img2.addMore': 'Add more',
      'img2.format': 'Format',
      'img2.quality': 'Quality',
      'img2.maxWidth': 'Max width (0 = original)',
      'img2.download': 'Download',
      'img2.copy': 'Copy',
      'img2.copied': 'Copied to clipboard',
      'img2.copyUnsupported': 'Clipboard image copy is not supported here',
      'img2.downloadAll': 'Download all',
      'img2.unsupported': 'This format is not supported by your browser',
      'img2.color': 'Color',
      'img2.size': 'Size',
      'img2.fontSize': 'Font size',

      // Compress
      'img2.nav.compress': 'Compress',
      'img2.nav.convert': 'Convert',
      'img2.nav.watermark': 'Watermark',
      'img2.nav.edit': 'Edit',
      'img2.nav.compose': 'Compose',
      'img2.nav.metadata': 'Metadata',
      'img2.compress.title': 'Compress Image',
      'img2.compress.sub': 'Shrink file size with adjustable quality — fully private.',
      'img2.before': 'Before',
      'img2.after': 'After',
      'img2.pngNote': 'PNG is lossless — quality has no effect. Try JPG or WebP to reduce size.',

      // Convert
      'img2.convert.title': 'Convert Image Format',
      'img2.convert.sub': 'Convert between PNG, JPG, WebP (and AVIF where supported). Batch ready.',

      // Watermark
      'img2.watermark.title': 'Watermark Image',
      'img2.watermark.sub': 'Add a text or image watermark with live preview.',
      'img2.wmType': 'Watermark type',
      'img2.wmText': 'Text',
      'img2.wmImage': 'Image',
      'img2.wmTextLabel': 'Watermark text',
      'img2.wmColor': 'Color',
      'img2.wmFontSize': 'Font size',
      'img2.wmImageLabel': 'Watermark image',
      'img2.wmPick': 'Choose image…',
      'img2.wmScale': 'Scale',
      'img2.wmPosition': 'Position',
      'img2.wmTile': 'Tile across image',
      'img2.wmMargin': 'Margin',
      'img2.wmOpacity': 'Opacity',
      'img2.wmRotation': 'Rotation',

      // Edit / annotate
      'img2.edit.title': 'Edit & Annotate',
      'img2.edit.sub': 'Doodle, add text, and redact with mosaic or blur. Undo/redo supported.',
      'img2.toolPen': 'Doodle',
      'img2.toolText': 'Add text',
      'img2.toolRedact': 'Redact',
      'img2.mosaic': 'Mosaic',
      'img2.blur': 'Blur',
      'img2.strength': 'Strength',
      'img2.undo': 'Undo',
      'img2.redo': 'Redo',
      'img2.typeHere': 'Type…',
      'img2.penHint': 'Drag on the image to draw freehand.',
      'img2.textHint': 'Click to place text · Enter to confirm · Esc to cancel.',
      'img2.redactHint': 'Drag a rectangle to hide that area.',

      // Metadata
      'img2.meta.title': 'Image Metadata',
      'img2.meta.sub': 'View and edit all metadata — EXIF, GPS, IPTC, XMP, PNG text. Everything stays on your device.',
      'img2.meta.tabView': 'View',
      'img2.meta.tabEdit': 'Edit',
      'img2.meta.reading': 'Reading metadata…',
      'img2.meta.readError': 'Could not read this file’s metadata.',
      'img2.meta.empty': '(empty)',
      'img2.meta.emptyTitle': 'No metadata found',
      'img2.meta.emptyDesc': 'This image has no embedded EXIF, GPS, IPTC, XMP, or text metadata.',
      'img2.meta.allTags': 'All tags',
      // Sections
      'img2.meta.secImage': 'Image',
      'img2.meta.secCamera': 'Camera',
      'img2.meta.secExposure': 'Exposure',
      'img2.meta.secDate': 'Date & Time',
      'img2.meta.secAuthor': 'Description & Rights',
      // GPS
      'img2.meta.gpsFound': 'Location embedded',
      'img2.meta.viewMap': 'View on map',
      'img2.meta.removeGps': 'Remove GPS',
      'img2.meta.gpsEdit': 'GPS location',
      'img2.meta.gpsEditHint': 'Decimal degrees. Leave both blank to remove location on save.',
      'img2.meta.lat': 'Latitude',
      'img2.meta.lon': 'Longitude',
      'img2.meta.gpsPairWarn': 'Enter both latitude and longitude, or leave both blank.',
      'img2.meta.gpsInvalid': 'Latitude must be −90…90 and longitude −180…180.',
      // Edit fields
      'img2.meta.fDescription': 'Description',
      'img2.meta.fArtist': 'Artist / Author',
      'img2.meta.fCopyright': 'Copyright',
      'img2.meta.fMake': 'Camera make',
      'img2.meta.fModel': 'Camera model',
      'img2.meta.fSoftware': 'Software',
      'img2.meta.fDate': 'Date taken',
      'img2.meta.saveBtn': 'Save metadata',
      'img2.meta.saved': 'Metadata saved',
      'img2.meta.savedReady': 'Saved image ready',
      'img2.meta.saveError': 'Could not save metadata.',
      'img2.meta.editFormatNote': 'Writing metadata is supported for JPEG. Saving creates a new copy — your original is untouched.',
      'img2.meta.editUnsupportedTitle': 'Editing not available for this format',
      'img2.meta.editUnsupportedDesc': 'Writing metadata is only supported for JPEG. {fmt} metadata is shown read-only; you can still strip it for privacy.',
      // Strip
      'img2.meta.stripNote': 'Strip every metadata block (EXIF, GPS, IPTC, XMP, text) before sharing.',
      'img2.meta.stripAll': 'Remove all metadata',
      'img2.meta.stripped': 'Metadata removed',
      'img2.meta.strippedReady': 'Clean image ready',
      'img2.meta.stripError': 'Could not strip metadata.',

      // Compose (multi-layer compositor)
      'img2.compose.title': 'Image Compositor',
      'img2.compose.sub': 'Stack images on one canvas — move, scale, rotate, reorder, and fade each layer, then export.',
      'img2.compose.drop': 'Drop images to start compositing',
      'img2.compose.hint': 'Drag a layer to move · corner handles to resize (hold Shift = free) · top handle to rotate (Shift = snap) · pinch to scale/rotate on touch.',
      'img2.compose.canvasSize': 'Canvas size',
      'img2.compose.background': 'Background',
      'img2.compose.bgTransparent': 'Transparent',
      'img2.compose.bgWhite': 'White',
      'img2.compose.bgBlack': 'Black',
      'img2.compose.bgCustom': 'Custom color',
      'img2.compose.width': 'Width',
      'img2.compose.height': 'Height',
      'img2.compose.preset.fit': 'Fit first image',
      'img2.compose.preset.sq': 'Square · 1080×1080',
      'img2.compose.preset.wide': 'Landscape · 1920×1080',
      'img2.compose.preset.story': 'Portrait · 1080×1920',
      'img2.compose.preset.photo': 'Photo · 1600×1200',
      'img2.compose.layers': 'Layers',
      'img2.compose.addLayer': 'Add',
      'img2.compose.hide': 'Hide',
      'img2.compose.show': 'Show',
      'img2.compose.moveUp': 'Move forward',
      'img2.compose.moveDown': 'Move backward',
      'img2.compose.transform': 'Selected layer',
      'img2.compose.size': 'Size',
      'img2.compose.toFront': 'To front',
      'img2.compose.toBack': 'To back',
      'img2.compose.duplicate': 'Duplicate',
      'img2.compose.resetLayer': 'Reset',

      // Invisible watermark
      'img2.nav.invisible': 'Invisible',
      'img2.inv.title': 'Invisible Watermark',
      'img2.inv.sub': 'Embed a hidden, robust mark that survives re-compression — then read it back. Fully private, on your device.',
      'img2.inv.tabEmbed': 'Embed',
      'img2.inv.tabDecode': 'Read',
      'img2.inv.content': 'Custom content',
      'img2.inv.contentHint': 'Up to 16 bytes (~16 letters / ~5 CJK chars). Longer content needs the verify page.',
      'img2.inv.bytesLeft': '{n} bytes left',
      'img2.inv.register': 'Register verify page',
      'img2.inv.registerHint': 'Registered content becomes publicly viewable at box.muran.tech and can be any length.',
      'img2.inv.registerFailed': 'Registration failed — the backend may be unavailable.',
      'img2.inv.uniform': 'Content for all',
      'img2.inv.overCap': 'Over the 16-byte limit by {n} — will be shortened',
      'img2.inv.duplicate': 'Make {n} versions',
      'img2.inv.versions': 'Versions',
      'img2.inv.generate': 'Generate',
      'img2.inv.generating': 'Generating…',
      'img2.inv.downloadZip': 'Download all (ZIP)',
      'img2.inv.tooSmall': 'Image is too small to hold the watermark (needs ≥ ~120×120).',
      'img2.inv.decDrop': 'Drop a watermarked image to read it',
      'img2.inv.decNone': 'No watermark detected, or the image is too degraded.',
      'img2.inv.fldContent': 'Content',
      'img2.inv.fldTime': 'Timestamp',
      'img2.inv.fldService': 'Service',
      'img2.inv.fldVersion': 'Version',
      'img2.inv.fldConfidence': 'Confidence',
      'img2.inv.registered': 'Registered at box.muran.tech',
      'img2.inv.viewVerify': 'Open verify page',
      'img2.inv.regNotFound': 'Marked as registered, but no record was found.',
      'img2.inv.robustNote': 'Survives JPEG re-compression, rescaling, and colour shifts. Not crop, rotation, or AI re-generation.',

      // Verify page (/w/:id)
      'img2.verify.title': 'Watermark record',
      'img2.verify.intro': 'Someone embedded an invisible watermark in an image and registered it on this site. This page shows the public record behind that mark.',
      'img2.verify.loading': 'Looking up…',
      'img2.verify.notFound': 'No record found for this id.',
      'img2.verify.notFoundDesc': 'The id may be mistyped, or this watermark was never registered here.',
      'img2.verify.fldId': 'Record id',
      'img2.verify.cta': 'Check an image for a watermark',
      'img2.verify.ctaHint': 'Got an image? Read its invisible watermark right in your browser — nothing is uploaded.',
      'img2.verify.service': 'Marked by box.muran.tech',
    },
    zh: {
      // Shared
      'img2.drop': '拖入图片',
      'img2.browse': '点击、拖入或粘贴 · PNG、JPG、WebP、GIF',
      'img2.dropBatch': '拖入图片',
      'img2.browseBatch': '点击、拖入或粘贴 · 支持多文件',
      'img2.change': '更换',
      'img2.remove': '移除',
      'img2.clear': '清空',
      'img2.addMore': '继续添加',
      'img2.format': '输出格式',
      'img2.quality': '质量',
      'img2.maxWidth': '最大宽度（0 = 原始）',
      'img2.download': '下载',
      'img2.copy': '复制',
      'img2.copied': '已复制到剪贴板',
      'img2.copyUnsupported': '当前环境不支持复制图片到剪贴板',
      'img2.downloadAll': '全部下载',
      'img2.unsupported': '当前浏览器不支持该格式',
      'img2.color': '颜色',
      'img2.size': '粗细',
      'img2.fontSize': '字号',

      // Compress
      'img2.nav.compress': '压缩',
      'img2.nav.convert': '转格式',
      'img2.nav.watermark': '水印',
      'img2.nav.edit': '编辑',
      'img2.nav.compose': '合成',
      'img2.nav.metadata': '元信息',
      'img2.compress.title': '压缩图片',
      'img2.compress.sub': '调节质量以减小文件体积 — 全程本地处理。',
      'img2.before': '压缩前',
      'img2.after': '压缩后',
      'img2.pngNote': 'PNG 为无损格式，质量无效。改用 JPG 或 WebP 可减小体积。',

      // Convert
      'img2.convert.title': '转换图片格式',
      'img2.convert.sub': '在 PNG、JPG、WebP（及支持时的 AVIF）之间转换，支持批量。',

      // Watermark
      'img2.watermark.title': '添加水印',
      'img2.watermark.sub': '添加文字或图片水印，实时预览。',
      'img2.wmType': '水印类型',
      'img2.wmText': '文字',
      'img2.wmImage': '图片',
      'img2.wmTextLabel': '水印文字',
      'img2.wmColor': '颜色',
      'img2.wmFontSize': '字号',
      'img2.wmImageLabel': '水印图片',
      'img2.wmPick': '选择图片…',
      'img2.wmScale': '缩放',
      'img2.wmPosition': '位置',
      'img2.wmTile': '平铺整图',
      'img2.wmMargin': '边距',
      'img2.wmOpacity': '不透明度',
      'img2.wmRotation': '旋转',

      // Edit / annotate
      'img2.edit.title': '编辑与标注',
      'img2.edit.sub': '涂鸦、添加文字、用马赛克或模糊打码。支持撤销/重做。',
      'img2.toolPen': '涂鸦',
      'img2.toolText': '添加文字',
      'img2.toolRedact': '打码',
      'img2.mosaic': '马赛克',
      'img2.blur': '模糊',
      'img2.strength': '强度',
      'img2.undo': '撤销',
      'img2.redo': '重做',
      'img2.typeHere': '输入…',
      'img2.penHint': '在图片上拖动即可自由绘制。',
      'img2.textHint': '点击放置文字 · 回车确认 · Esc 取消。',
      'img2.redactHint': '拖出一个矩形以遮盖该区域。',

      // Metadata
      'img2.meta.title': '图片元信息',
      'img2.meta.sub': '查看并编辑全部元数据 — EXIF、GPS、IPTC、XMP、PNG 文本。全程本地处理。',
      'img2.meta.tabView': '查看',
      'img2.meta.tabEdit': '编辑',
      'img2.meta.reading': '正在读取元数据…',
      'img2.meta.readError': '无法读取该文件的元数据。',
      'img2.meta.empty': '（空）',
      'img2.meta.emptyTitle': '未发现元数据',
      'img2.meta.emptyDesc': '该图片不含任何 EXIF、GPS、IPTC、XMP 或文本元数据。',
      'img2.meta.allTags': '全部标签',
      // Sections
      'img2.meta.secImage': '图像',
      'img2.meta.secCamera': '相机',
      'img2.meta.secExposure': '曝光',
      'img2.meta.secDate': '日期与时间',
      'img2.meta.secAuthor': '描述与版权',
      // GPS
      'img2.meta.gpsFound': '已嵌入位置信息',
      'img2.meta.viewMap': '在地图中查看',
      'img2.meta.removeGps': '移除 GPS',
      'img2.meta.gpsEdit': 'GPS 位置',
      'img2.meta.gpsEditHint': '十进制度。两项均留空则在保存时移除位置。',
      'img2.meta.lat': '纬度',
      'img2.meta.lon': '经度',
      'img2.meta.gpsPairWarn': '请同时填写经纬度，或都留空。',
      'img2.meta.gpsInvalid': '纬度须为 −90…90，经度须为 −180…180。',
      // Edit fields
      'img2.meta.fDescription': '描述',
      'img2.meta.fArtist': '作者',
      'img2.meta.fCopyright': '版权',
      'img2.meta.fMake': '相机厂商',
      'img2.meta.fModel': '相机型号',
      'img2.meta.fSoftware': '软件',
      'img2.meta.fDate': '拍摄日期',
      'img2.meta.saveBtn': '保存元数据',
      'img2.meta.saved': '元数据已保存',
      'img2.meta.savedReady': '已生成保存后的图片',
      'img2.meta.saveError': '无法保存元数据。',
      'img2.meta.editFormatNote': '写入元数据仅支持 JPEG。保存会生成新副本，原图不受影响。',
      'img2.meta.editUnsupportedTitle': '该格式不支持编辑',
      'img2.meta.editUnsupportedDesc': '写入元数据仅支持 JPEG。{fmt} 的元数据为只读显示；仍可为隐私一键清除。',
      // Strip
      'img2.meta.stripNote': '分享前清除全部元数据（EXIF、GPS、IPTC、XMP、文本）。',
      'img2.meta.stripAll': '清除全部元数据',
      'img2.meta.stripped': '元数据已清除',
      'img2.meta.strippedReady': '已生成干净的图片',
      'img2.meta.stripError': '无法清除元数据。',

      // Compose(多图层合成)
      'img2.compose.title': '图片合成',
      'img2.compose.sub': '在同一画布上叠放多张图片 —— 移动、缩放、旋转、调整层级与不透明度，然后导出。',
      'img2.compose.drop': '拖入图片开始合成',
      'img2.compose.hint': '拖动图层可移动 · 拖角柄缩放（按住 Shift 自由缩放）· 顶部手柄旋转（Shift 吸附）· 触屏双指缩放/旋转。',
      'img2.compose.canvasSize': '画布尺寸',
      'img2.compose.background': '背景',
      'img2.compose.bgTransparent': '透明',
      'img2.compose.bgWhite': '白色',
      'img2.compose.bgBlack': '黑色',
      'img2.compose.bgCustom': '自定义颜色',
      'img2.compose.width': '宽度',
      'img2.compose.height': '高度',
      'img2.compose.preset.fit': '适应首张图片',
      'img2.compose.preset.sq': '正方形 · 1080×1080',
      'img2.compose.preset.wide': '横版 · 1920×1080',
      'img2.compose.preset.story': '竖版 · 1080×1920',
      'img2.compose.preset.photo': '照片 · 1600×1200',
      'img2.compose.layers': '图层',
      'img2.compose.addLayer': '添加',
      'img2.compose.hide': '隐藏',
      'img2.compose.show': '显示',
      'img2.compose.moveUp': '上移一层',
      'img2.compose.moveDown': '下移一层',
      'img2.compose.transform': '选中图层',
      'img2.compose.size': '大小',
      'img2.compose.toFront': '置顶',
      'img2.compose.toBack': '置底',
      'img2.compose.duplicate': '复制',
      'img2.compose.resetLayer': '重置',

      // Invisible watermark
      'img2.nav.invisible': '隐水印',
      'img2.inv.title': '隐水印',
      'img2.inv.sub': '嵌入一层隐藏、抗压的水印，重新压缩后仍可读出。全程本地、完全私密。',
      'img2.inv.tabEmbed': '写入',
      'img2.inv.tabDecode': '读取',
      'img2.inv.content': '自定义内容',
      'img2.inv.contentHint': '最多 16 字节（约 16 个字母 / 约 5 个汉字）。更长内容需用验证页。',
      'img2.inv.bytesLeft': '还剩 {n} 字节',
      'img2.inv.register': '注册验证页',
      'img2.inv.registerHint': '注册后内容将在 box.muran.tech 公开可查，且长度不限。',
      'img2.inv.registerFailed': '注册失败 —— 后端可能不可用。',
      'img2.inv.uniform': '统一内容',
      'img2.inv.overCap': '超出 16 字节上限 {n} 字节，生成时将截断',
      'img2.inv.duplicate': '生成 {n} 个版本',
      'img2.inv.versions': '版本数',
      'img2.inv.generate': '生成',
      'img2.inv.generating': '生成中…',
      'img2.inv.downloadZip': '全部下载（ZIP）',
      'img2.inv.tooSmall': '图片太小，放不下水印（需 ≥ 约 120×120）。',
      'img2.inv.decDrop': '拖入带水印的图片以读取',
      'img2.inv.decNone': '未检测到水印，或图片损毁过重。',
      'img2.inv.fldContent': '内容',
      'img2.inv.fldTime': '时间戳',
      'img2.inv.fldService': '服务',
      'img2.inv.fldVersion': '版本',
      'img2.inv.fldConfidence': '置信度',
      'img2.inv.registered': '已在 box.muran.tech 注册',
      'img2.inv.viewVerify': '打开验证页',
      'img2.inv.regNotFound': '标记为已注册，但未找到记录。',
      'img2.inv.robustNote': '可抵抗 JPEG 重压缩、缩放与调色；不抗裁剪、旋转或 AI 重绘。',

      // Verify page (/w/:id)
      'img2.verify.title': '水印记录',
      'img2.verify.intro': '有人在一张图片中嵌入了隐水印，并在本站注册了它。本页展示该水印对应的公开记录。',
      'img2.verify.loading': '查询中…',
      'img2.verify.notFound': '未找到该 id 对应的记录。',
      'img2.verify.notFoundDesc': '可能是 id 输入有误，或这个水印从未在本站注册。',
      'img2.verify.fldId': '记录 id',
      'img2.verify.cta': '检测你手里的图片',
      'img2.verify.ctaHint': '手里有图？直接在浏览器里读取它的隐水印 —— 不会上传任何文件。',
      'img2.verify.service': '由 box.muran.tech 标记',
    },
  },
}
